feedback/urls.py
from django.urls import path
from .views import FeedbackView, FeedbackDeleteView

app_name = 'feedback'

urlpatterns = [
    path('', FeedbackView.as_view(), name='feedback-view'),
    path('<int:pk>/delete/', FeedbackDeleteView.as_view(), name='feedback-delete'),
]

home/urls.py
from django.urls import path
from .views import HomePageView, AboutView, ServicesView, PricingView, ContactView, E_OfferView, PrivacyPolicyView, TermsOfServicesView


app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name="home-page"),
    path('about/', AboutView.as_view(), name="about"),
    path('services/', ServicesView.as_view(), name="services"),
    path('pricing/', PricingView.as_view(), name="pricing"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('mycoes-offers/', E_OfferView.as_view(), name="e-offer"),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name="privacy-policy"),
    path('terms-of-services/', TermsOfServicesView.as_view(), name="terms-of-services"),
]

website/urls.py
from django.contrib import admin
from user_profile.views import CustomLogoutView
from django.urls import path, include
from django.views.generic import TemplateView
from home.views import Custom404View, Custom500View


urlpatterns = [
    path('tohid/admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('auth/', include('magiclink.urls', namespace='magiclink')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('cookies/', include('cookie_consent.urls')),
    path('profile/', include('user_profile.urls', namespace='user_profile')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('support/', include('support.urls', namespace='support')),
    path('sitemap.xml/', TemplateView.as_view(template_name='sitemap.xml', content_type='application/xml')),
    path('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('logout/', CustomLogoutView.as_view(), name='custom_logout'),
]


handler404 = Custom404View.as_view()
handler500 = Custom500View.as_view()

feedback/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text_feedback = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

feedback/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['text_feedback',]
        
        
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text_feedback'].label = '' 
        
        self.fields['text_feedback'].widget.attrs.update({'class': 'text_feedback'})
    

feedback/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import generic

from .forms import FeedbackForm
from .models import Feedback



class FeedbackView(LoginRequiredMixin, generic.CreateView, generic.ListView):
    template_name = 'feedback.html'
    form_class = FeedbackForm
    model = Feedback


    def get_success_url(self):
        return reverse('feedback:feedback-view')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        feedbacks = Feedback.objects.all()  # Retrieve all feedbacks from the database
        feedback_count = feedbacks.count()  # Count the number of feedbacks
        context['feedbacks'] = feedbacks
        context['feedback_count'] = feedback_count
        return context
    

class FeedbackDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Feedback
    template_name = 'feedback.html' 
    
    def get_success_url(self):
        return reverse('feedback:feedback-view')

feedback/templates/feedback.html
{% extends 'base.html' %}
{% load static %}
{% block canonical_url %}https://mycoes.com/feedback/{% endblock canonical_url %}
{% block title %}MyCoes User Feedbacks{% endblock title %}
{% block meta_description %}Your opinion matters to us. Share your thoughts on MyCoes and help us improve. Leave your feedback on our platform and be heard.{% endblock meta_description %}


{% block content %}

<div class="m-auto w-full sm:w-11/12 md:w-10/12 lg:w-9/12">
   <div class="mt-28 sm:mt-32 md:mt-36">

  
  
    <div class="text-left m-4">
      <p class="text-4xl sm:text-5xl font-OpenSans font-normal text-black dark:text-white">Feedback & Reviews</p>
    </div>
  


    <div class="mt-4 md:mt-10 mx-4 flex items-center gap-4">
      <div class="rounded-full text-white dark:text-black w-8 h-8 flex items-center justify-center bg-black dark:bg-white">{{ user.username.0|default_if_none:""|upper }}</div>              
      <div class="pb-8 w-9/12 pt-8">
          <div class="w-full border border-black dark:border-gray-400 rounded-xl">
              
                <div class="w-full">
                      <form method="POST" class="flex">
                          {% csrf_token %}
                          {{ form }}
                          <button type="submit" class="text-black dark:text-white font-Roboto font-normal text-lg sm:text-xl p-3 -mb-4">Submit</button>
                        </form>
               </div>            
          </div>
        </div>

      </div>


<div>
<p class="text-xl font-OpenSans font-normal text-black dark:text-white m-4">{{ feedback_count }} Feedbacks</p>
</div>


  <div class="mt-10 mb-20">
    <div class="w-full overflow-y-hidden">
     
      
      {% for feedback in object_list %}
      <div >
          <div class="flex justify-between mx-4">
            <div class="flex gap-4">
              <div class="rounded-full text-white dark:text-black w-8 h-8 flex items-center justify-center bg-black dark:bg-white">{{ feedback.user.username.0|default_if_none:""|upper }}</div>              
              <div><p class="text-sm font-Roboto font-bold text-black dark:text-white">{{ feedback.user.username }}</p></div>
              <div><p class="text-sm font-Roboto font-normal text-black dark:text-white">{{ feedback.timestamp|date }}</p></div>
            </div>
            <div>
             {% if feedback.user == user %}
            <form method="post" action="{% url 'feedback:feedback-delete' feedback.pk %}">
              {% csrf_token %}

             
<!-- Three Doted Menu Icon -->
<div type="submit" class="flex justify-between hover:cursor-pointer" aria-label="Breadcrumb">
  <ol class="inline-flex items-center mb-3 sm:mb-0">
    <li>
      <div class="flex items-center">
        <span id="dropdownProject" data-dropdown-toggle="dropdown-project">
          <svg class="fill-black dark:fill-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" height="30" viewBox="0 -960 960 960" width="30"><path d="M240-400q-33 0-56.5-23.5T160-480q0-33 23.5-56.5T240-560q33 0 56.5 23.5T320-480q0 33-23.5 56.5T240-400Zm240 0q-33 0-56.5-23.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 33-23.5 56.5T480-400Zm240 0q-33 0-56.5-23.5T640-480q0-33 23.5-56.5T720-560q33 0 56.5 23.5T800-480q0 33-23.5 56.5T720-400Z"/></svg>
          </span>
        <button type="submit" id="dropdown-project" class="z-20 hidden bg-white divide-y divide-gray-100 rounded-lg w-32 dark:bg-black border border-gray-400 dark:border-gray-700">
          <ul class="py-2 text-sm text-black dark:text-white" aria-labelledby="dropdownDefault">
            <li class="block px-4 py-2">
              Delete
            </li>
          </ul>
        </button>   
      </div>
    </li>
  </ol>
</div>

      
            </form>
            {% endif %}
          </div>
        </div>
          <div class="mx-14 my-4 border-b border-slate-600 dark:border-slate-500"><p class="text-base xsm:text-xl font-Content font-normal tracking-wide text-black dark:text-white m-4">{{ feedback.text_feedback }}</p></div>
        </div>

      
  
  
      {% empty %}
      <div>
        <p class="font-OpenSans text-3xl m-4 text-black dark:text-white">No Feedbacks yet.</p>
      </div>
      {% endfor %}

    </div>
  </div>
  
  
      </div>
  </div>
{% endblock content %}