feedback/urls.py
from django.urls import path
from .views import FeedbackView, FeedbackDeleteView

app_name = 'feedback'

urlpatterns = [
    path('', FeedbackView.as_view(), name='feedback-view'),
    path('<int:pk>/delete/', FeedbackDeleteView.as_view(), name='feedback-delete'),
]

home/urls.py
from django.urls import path
from .views import HomePageView, AboutView, ServicesView, PricingView, ContactView, E_OfferView, PrivacyPolicyView, TermsOfServicesView


app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name="home-page"),
    path('about/', AboutView.as_view(), name="about"),
    path('services/', ServicesView.as_view(), name="services"),
    path('pricing/', PricingView.as_view(), name="pricing"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('mycoes-offers/', E_OfferView.as_view(), name="e-offer"),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name="privacy-policy"),
    path('terms-of-services/', TermsOfServicesView.as_view(), name="terms-of-services"),
]

user_profile/urls.py
from django.urls import  path, re_path
from .views import  OfferView, BillingView, PaypalPaymentView, PaypalPaymentSuccessView, ProfileTranscationsView

app_name = 'user_profile'

urlpatterns = [
    path('offer/', OfferView.as_view(), name="make-offer"),
    path('offers-billing/', BillingView.as_view(), name='offers-billing'),
    re_path(r'^payments/paypal/(?P<next_milestone_id>[\w-]+)/$', PaypalPaymentView.as_view(), name='paypal-payment'),
    re_path(r'^payments/paypal/success/(?P<next_milestone_id>[\w-]+)/$', PaypalPaymentSuccessView.as_view(), name='paypal-payment-success'),
    path('transctions/', ProfileTranscationsView.as_view(), name='transctions'),
]

website/urls.py
from django.contrib import admin
from user_profile.views import CustomLogoutView
from django.urls import path, include
from django.views.generic import TemplateView
from home.views import Custom404View, Custom500View


urlpatterns = [
    path('tohid/admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('auth/', include('magiclink.urls', namespace='magiclink')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('cookies/', include('cookie_consent.urls')),
    path('profile/', include('user_profile.urls', namespace='user_profile')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('support/', include('support.urls', namespace='support')),
    path('sitemap.xml/', TemplateView.as_view(template_name='sitemap.xml', content_type='application/xml')),
    path('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('logout/', CustomLogoutView.as_view(), name='custom_logout'),
]


handler404 = Custom404View.as_view()
handler500 = Custom500View.as_view()

templates/base/footer.html
<div class="w-full md:w-10/12 lg:w-9/12 mx-auto py-4 bottom-0">
  <div class="sm:flex sm:items-center sm:justify-between">
      <div>
      <a href="/" class="font-OpenSans font-extrabold text-4xl text-black dark:text-white">MyCoes</a>
      <span class="block mt-4 mb-4 text-sm text-black dark:text-white">© 2023 <a href="/" class="hover:underline">MyCoes™</a>. All Rights Reserved.</span>
     </div>

      <ul class="flex flex-wrap items-center leading-relaxed mt-3 mb-6 text-sm font-medium sm:mb-0 sm:mt-0 text-black dark:text-white">
        
          <li>
              <a href="{% url 'home:privacy-policy' %}" class="mr-4 text-lg  hover:underline md:mr-6">Privacy & Policy</a>
          </li>
          <li>
              <a href="{% url 'home:terms-of-services' %}" class="mr-4 text-lg  hover:underline md:mr-6">Terms of services</a>
          </li>
          <li>
              <a href="{% url 'feedback:feedback-view' %}" class="mr-4 text-lg  hover:underline md:mr-6">Feedback</a>
          </li>

          <li>
              <a href="{% url 'support:home' %}" class="mr-4 text-lg  hover:underline md:mr-6">Support</a>
          </li>
         
      </ul>

      
      <div class="border border-black dark:border-white flex w-40 text-center">
          <a
            id="theme-switcher"
            class="block w-full whitespace-nowrap  px-3 py-2 text-sm font-normal dark:text-white bg-white dark:bg-black active:bg-black active:text-white active:no-underline disabled:pointer-events-none disabled:bg-transparent disabled:text-black hover:bg-slate-400"
            href="#"
            data-theme="light">
            <div class="pointer-events-none">
             
              <span data-theme-name="light">Light</span>
            </div>
          </a>
          <a
            id="theme-switcher"
            class="block w-full whitespace-nowrap bg-transparent px-3 py-2 text-sm font-normal dark:text-black bg-black dark:bg-white active:bg-white active:text-black active:no-underline disabled:pointer-events-none disabled:bg-transparent disabled:text-black hover:bg-slate-400"
            href="#"
            data-theme="dark"
            data-te-dropdown-item-ref>
            <div class="pointer-events-none">
              <span data-theme-name="dark">Dark</span>
            </div>
          </a>
        </div>

  </div>

  <div class="bg-white dark:bg-black border-t border-slate-500 dark:border-slate-700 max-md:px-4 m-4 flex items-center justify-center gap-4 pt-10">
    
    <a href="https://www.facebook.com/profile.php?id=61555244344662">
      <?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 fill-black dark:fill-white" alt="facebook" viewBox="0 0 50 50" width="25px" height="25px"><path d="M41,4H9C6.24,4,4,6.24,4,9v32c0,2.76,2.24,5,5,5h32c2.76,0,5-2.24,5-5V9C46,6.24,43.76,4,41,4z M37,19h-2c-2.14,0-3,0.5-3,2 v3h5l-1,5h-4v15h-5V29h-4v-5h4v-3c0-4,2-7,6-7c2.9,0,4,1,4,1V19z"/></svg>
    </a>

    <a href="https://www.linkedin.com/company/99204854">
     <?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 fill-black dark:fill-white" alt="linkedin" viewBox="0 0 50 50" width="25px" height="25px">    <path d="M41,4H9C6.24,4,4,6.24,4,9v32c0,2.76,2.24,5,5,5h32c2.76,0,5-2.24,5-5V9C46,6.24,43.76,4,41,4z M17,20v19h-6V20H17z M11,14.47c0-1.4,1.2-2.47,3-2.47s2.93,1.07,3,2.47c0,1.4-1.12,2.53-3,2.53C12.2,17,11,15.87,11,14.47z M39,39h-6c0,0,0-9.26,0-10 c0-2-1-4-3.5-4.04h-0.08C27,24.96,26,27.02,26,29c0,0.91,0,10,0,10h-6V20h6v2.56c0,0,1.93-2.56,5.81-2.56 c3.97,0,7.19,2.73,7.19,8.26V39z"/></svg>
    </a>

    <a href="https://www.instagram.com/real_mycoes">
       <?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 fill-black dark:fill-white" alt="instagram" viewBox="0 0 50 50" width="25px" height="25px">    <path d="M 16 3 C 8.83 3 3 8.83 3 16 L 3 34 C 3 41.17 8.83 47 16 47 L 34 47 C 41.17 47 47 41.17 47 34 L 47 16 C 47 8.83 41.17 3 34 3 L 16 3 z M 37 11 C 38.1 11 39 11.9 39 13 C 39 14.1 38.1 15 37 15 C 35.9 15 35 14.1 35 13 C 35 11.9 35.9 11 37 11 z M 25 14 C 31.07 14 36 18.93 36 25 C 36 31.07 31.07 36 25 36 C 18.93 36 14 31.07 14 25 C 14 18.93 18.93 14 25 14 z M 25 16 C 20.04 16 16 20.04 16 25 C 16 29.96 20.04 34 25 34 C 29.96 34 34 29.96 34 25 C 34 20.04 29.96 16 25 16 z"/></svg>
    </a>

    <a href="https://wa.me/918431944801?text=Hello%20from%20websiteWhatsapp">
      <?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 fill-black dark:fill-white" alt="whatsapp" viewBox="0 0 50 50" width="25px" height="25px">    <path d="M25,2C12.318,2,2,12.318,2,25c0,3.96,1.023,7.854,2.963,11.29L2.037,46.73c-0.096,0.343-0.003,0.711,0.245,0.966 C2.473,47.893,2.733,48,3,48c0.08,0,0.161-0.01,0.24-0.029l10.896-2.699C17.463,47.058,21.21,48,25,48c12.682,0,23-10.318,23-23 S37.682,2,25,2z M36.57,33.116c-0.492,1.362-2.852,2.605-3.986,2.772c-1.018,0.149-2.306,0.213-3.72-0.231 c-0.857-0.27-1.957-0.628-3.366-1.229c-5.923-2.526-9.791-8.415-10.087-8.804C15.116,25.235,13,22.463,13,19.594 s1.525-4.28,2.067-4.864c0.542-0.584,1.181-0.73,1.575-0.73s0.787,0.005,1.132,0.021c0.363,0.018,0.85-0.137,1.329,1.001 c0.492,1.168,1.673,4.037,1.819,4.33c0.148,0.292,0.246,0.633,0.05,1.022c-0.196,0.389-0.294,0.632-0.59,0.973 s-0.62,0.76-0.886,1.022c-0.296,0.291-0.603,0.606-0.259,1.19c0.344,0.584,1.529,2.493,3.285,4.039 c2.255,1.986,4.158,2.602,4.748,2.894c0.59,0.292,0.935,0.243,1.279-0.146c0.344-0.39,1.476-1.703,1.869-2.286 s0.787-0.487,1.329-0.292c0.542,0.194,3.445,1.604,4.035,1.896c0.59,0.292,0.984,0.438,1.132,0.681 C37.062,30.587,37.062,31.755,36.57,33.116z"/></svg>
    </a>
  
   
  </div>

  </div>

templates/base/navbar.html
<nav  class="bg-white dark:bg-black border-b border-slate-400 dark:border-slate-800 z-50 fixed w-full">
  <div class="w-full md:w-10/12 lg:w-9/12 flex flex-wrap items-center justify-between mx-auto my-auto max-md:px-4 py-4">
    
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <span class="font-OpenSans font-extrabold text-4xl text-black dark:text-white">MyCoes</span>
  </a>
    <button data-collapse-toggle="navbar-solid-bg" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-full lg:hidden hover:bg-gray-200 focus:outline-none dark:text-gray-400 dark:hover:bg-gray-700" aria-controls="navbar-solid-bg" aria-expanded="false">
        <span class="sr-only">menu</span>
        <svg class="w-5 h-5 fill-black dark:fill-white" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="100" height="100" viewBox="0 0 26 26">
          <path d="M 0 4 L 0 6 L 26 6 L 26 4 Z M 0 12 L 0 14 L 26 14 L 26 12 Z M 0 20 L 0 22 L 26 22 L 26 20 Z"></path>
          </svg>

    </button>
    <div class="hidden w-full lg:block lg:w-auto" id="navbar-solid-bg">
      <ul class="flex flex-col font-medium mt-16 rounded-lg lg:space-x-8 rtl:space-x-reverse lg:flex-row lg:mt-0 lg:border-0 lg:bg-transparent lg:dark:bg-transparent">
        
        <li><a href="/" class="font-Roboto tracking-wider font-light text-xl text-black dark:text-white lg:hover:underline block py-2 px-3 lg:p-0 lg:hover:bg-transparent lg:border-0  dark:hover:text-white lg:dark:hover:bg-transparent border-b border-gray-600 max-lg:pt-8 max-lg:hover:bg-gray-200 max-lg:dark:hover:bg-gray-700">Home</a></li>
        <li><a href="{% url 'home:about' %}" class="font-Roboto tracking-wider font-light text-xl text-black dark:text-white lg:hover:underline block py-2 px-3 lg:p-0 lg:hover:bg-transparent lg:border-0  dark:hover:text-white lg:dark:hover:bg-transparent border-b border-gray-600 max-lg:pt-8 max-lg:hover:bg-gray-200 max-lg:dark:hover:bg-gray-700">About us</a></li>
        <li><a href="{% url 'home:services' %}" class="font-Roboto tracking-wider font-light text-xl text-black dark:text-white lg:hover:underline block py-2 px-3 lg:p-0 lg:hover:bg-transparent lg:border-0  dark:hover:text-white lg:dark:hover:bg-transparent border-b border-gray-600 max-lg:pt-8 max-lg:hover:bg-gray-200 max-lg:dark:hover:bg-gray-700">Services</a></li>
        <li><a href="{% url 'home:pricing' %}" class="font-Roboto tracking-wider font-light text-xl text-black dark:text-white lg:hover:underline block py-2 px-3 lg:p-0 lg:hover:bg-transparent lg:border-0  dark:hover:text-white lg:dark:hover:bg-transparent border-b border-gray-600 max-lg:pt-8 max-lg:hover:bg-gray-200 max-lg:dark:hover:bg-gray-700">Pricing</a></li>
        <li><a href="{% url 'home:contact' %}" class="font-Roboto tracking-wider font-light text-xl text-black dark:text-white lg:hover:underline block py-2 px-3 lg:p-0 lg:hover:bg-transparent lg:border-0  dark:hover:text-white lg:dark:hover:bg-transparent border-b border-gray-600 max-lg:pt-8 max-lg:hover:bg-gray-200 max-lg:dark:hover:bg-gray-700">Contact</a></li>
        <li><a href="{% url 'user_profile:offers-billing' %}" class="font-Roboto tracking-wider font-light text-xl text-black dark:text-white lg:hover:underline block py-2 px-3 lg:p-0 lg:hover:bg-transparent lg:border-0  dark:hover:text-white lg:dark:hover:bg-transparent border-b border-gray-600 max-lg:pt-8 max-lg:hover:bg-gray-200 max-lg:dark:hover:bg-gray-700">Profile</a></li>
        
      </ul>
    </div>
  </div>
</nav>