home/urls.py
from django.urls import path
from .views import HomePageView, AboutView, ServicesView, PricingView, ContactView, E_OfferView, PrivacyPolicyView, TermsOfServicesView


app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name="home-page"),
    path('about/', AboutView.as_view(), name="about"),
    path('services/', ServicesView.as_view(), name="services"),
    path('pricing/', PricingView.as_view(), name="pricing"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('mycoes-offers/', E_OfferView.as_view(), name="e-offer"),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name="privacy-policy"),
    path('terms-of-services/', TermsOfServicesView.as_view(), name="terms-of-services"),
]

user_profile/urls.py
from django.urls import  path, re_path
from .views import  OfferView, BillingView, PaypalPaymentView, PaypalPaymentSuccessView, ProfileTranscationsView

app_name = 'user_profile'

urlpatterns = [
    path('offer/', OfferView.as_view(), name="make-offer"),
    path('offers-billing/', BillingView.as_view(), name='offers-billing'),
    re_path(r'^payments/paypal/(?P<next_milestone_id>[\w-]+)/$', PaypalPaymentView.as_view(), name='paypal-payment'),
    re_path(r'^payments/paypal/success/(?P<next_milestone_id>[\w-]+)/$', PaypalPaymentSuccessView.as_view(), name='paypal-payment-success'),
    path('transctions/', ProfileTranscationsView.as_view(), name='transctions'),
]

website/urls.py
from django.contrib import admin
from user_profile.views import CustomLogoutView
from django.urls import path, include
from django.views.generic import TemplateView
from home.views import Custom404View, Custom500View


urlpatterns = [
    path('tohid/admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('auth/', include('magiclink.urls', namespace='magiclink')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('cookies/', include('cookie_consent.urls')),
    path('profile/', include('user_profile.urls', namespace='user_profile')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('support/', include('support.urls', namespace='support')),
    path('sitemap.xml/', TemplateView.as_view(template_name='sitemap.xml', content_type='application/xml')),
    path('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('logout/', CustomLogoutView.as_view(), name='custom_logout'),
]


handler404 = Custom404View.as_view()
handler500 = Custom500View.as_view()

src/offers/models.py
from django.db import models

user_profile/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
    
    
class OfferMilestone(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    milestone_number = models.PositiveIntegerField()
    ammount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    percentage = models.CharField(max_length=10, blank=True, null=True)
    paid = models.BooleanField(default=False)
    offer = models.ForeignKey('Offer', on_delete=models.CASCADE, related_name='milestones')
    created_at = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=255, blank=True, null=True)
    transaction_date = models.DateTimeField(blank=True, null=True)
    
    class Meta:
        unique_together = ['offer', 'milestone_number']

    

class Offer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=70)
    description = models.TextField()
    timeline = models.CharField(max_length=70)
    budget = models.CharField(max_length=70)
    attached_files = models.FileField(upload_to='uploads/', null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
       
    

user_profile/views.py
from django.db.models import Sum
from time import sleep
from django.http import Http404
from django.shortcuts import redirect, render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.contrib import messages
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import OfferForm
from .models import Offer, OfferMilestone
from django.contrib import messages
from django.conf import settings
from .forms import CustomPayPalPaymentsForm
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt




class OfferView(LoginRequiredMixin, CreateView):
    template_name = 'offer.html'
    form_class = OfferForm
    success_url = reverse_lazy('user_profile:offers-billing')  # Define the URL to redirect to after successful form submission

    def form_valid(self, form):
        # Set the user field to the authenticated user and save the form
        form.instance.user = self.request.user
        form.save()
        messages.success(self.request, "Your offer has been submitted successfully. To proceed, click on your preferred communication platforms for the next steps.")
        sleep(2.5)
        return super().form_valid(form)
    
    

class BillingView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'billing_page.html'

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user_offers = Offer.objects.filter(user=self.request.user)

            offers_data = []

            for offer in user_offers:
                # Retrieve milestones specific to the selected offer
                all_offer_milestones = offer.milestones.all()
                offer_milestones = offer.milestones.filter(paid=False).order_by('created_at')
                next_milestone = offer_milestones.first()

                total_ammount = all_offer_milestones.aggregate(sum_ammount=Sum('ammount'))['sum_ammount'] or 0
                paid_ammount = offer.milestones.filter(paid=True).aggregate(sum_ammount=Sum('ammount'))['sum_ammount'] or 0
                remaining_ammount = total_ammount - paid_ammount


                offers_data.append({
                    'offer': offer,
                    'all_offer_milestones': all_offer_milestones,
                    'next_milestone': next_milestone,
                    'total_ammount': total_ammount,
                    'remaining_ammount': remaining_ammount,
                })

            # Update the context with the new data
            context.update({
                'user_offers': user_offers,
                'offers_data': offers_data,
            })

        return self.render_to_response(context)
    
    def post(self, request, *args, **kwargs):
        next_milestone_id = request.POST.get('next_milestone_id')
        request.session['next_milestone_id'] = next_milestone_id

        sleep(1)
        return redirect('user_profile:paypal-payment', next_milestone_id=next_milestone_id)
    
    
@method_decorator(csrf_exempt, name='dispatch')
class PaypalPaymentView(LoginRequiredMixin, generic.View):
    def get(self, request, *args, **kwargs):
        # Retrieve milestone data from sessions
        next_milestone_id = self.request.session.get('next_milestone_id')

        try:
            # Check if next_milestone_id is present
            if not next_milestone_id:
                raise Http404
            # Retrieve the milestone using next_milestone_id
            milestone = OfferMilestone.objects.get(id=next_milestone_id)
        except OfferMilestone.DoesNotExist:
            # Handle the case where the milestone is not found
            raise Http404
        
        paypal_dict = {
            'business': settings.PAYPAL_RECEIVER_EMAIL,
            'amount': milestone.ammount, 
            'item_name': milestone.offer.title,  
            'invoice': str(milestone.id), 
            'item_number': str(milestone.milestone_number),
            'currency_code': 'USD', 
            'notify_url': f'http://{request.get_host()}{reverse("paypal-ipn")}',
            'return_url': f'http://{request.get_host()}{reverse("user_profile:paypal-payment-success", kwargs={"next_milestone_id": next_milestone_id})}',
            'cancel_return': f'http://{request.get_host()}{reverse("user_profile:paypal-payment", kwargs={"next_milestone_id": next_milestone_id})}?message=cancel',

        }

        form = CustomPayPalPaymentsForm(initial=paypal_dict)
        
        context = {
            'form': form,
            'milestone': milestone  
        }
        
        message = request.GET.get('message', None)

        if message == 'notify':
            messages.info(request, 'Something happened on the Paypal side, Please retry.')
        elif message == 'cancel':
            messages.warning(request, 'Payment was canceled.')

        return render(request, 'paypal-payment.html', context)

    def dispatch(self, request, *args, **kwargs):
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            # Redirect to your custom 404 page
            return render(request, '404.html', status=404)
    
    
    

class PaypalPaymentSuccessView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'paypal-payment-success.html' 
    


class ProfileTranscationsView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'profile-transcations.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Retrieve paid transactions
        transactions = OfferMilestone.objects.filter(offer__user=self.request.user, paid=True)

        context['transactions'] = transactions
        return context  
    

  

class CustomLogoutView(LoginRequiredMixin, LogoutView):
  def get_success_url(self):
    success_url = super(CustomLogoutView, self).get_success_url()
    messages.add_message(
      self.request, messages.SUCCESS,
      'You have successfully logged out.'
    )
    return reverse('home:home-page')   

user_profile/templates/billing_page.html
{% extends 'profile.html' %}

{% block profile-content %}
<div class="mx-4 mb-20 z-50">
    <!-- Offer content -->
    {% if user_offers %}
        {% for offer_data in offers_data %}
            <div class="mb-12 mt-4 pb-6 border-b border-black dark:border-gray-400">
                <div>
                    <p class="text-4xl md:text-5xl leading-snug md:leading-snug font-Inter font-bold tracking-wide text-black dark:text-white">{{ offer_data.offer.title }}</p>
                </div>
                <div class="mt-4">
                    <p class="text-base sm:text-xl font-OpenSans font-normal tracking-wide leading-relaxed sm:leading-relaxed text-black dark:text-white">{{ offer_data.offer.timestamp|date }}</p>
                </div>
                <div class="mt-4">
                    <p class="text-base sm:text-xl font-Content font-normal tracking-wide leading-relaxed sm:leading-relaxed text-black dark:text-white">{{ offer_data.offer.description }}</p>
                </div>

                
                {% if offer_data.all_offer_milestones %}
                   
                 <!-- Pricing related -->
                <div class="relative w-full overflow-x-auto mt-10 border border-black dark:border-gray-400">
                    <table class="w-full text-sm text-left rtl:text-right text-black dark:text-gray-400">
                        <thead class="text-xs text-gray-700 uppercase bg dark:bg-black dark:text-gray-400 border-b border-black dark:border-gray-400">
                            <tr>
                                <th scope="col" class="px-6 py-3">Milestones</th>
                                <th scope="col" class="px-6 py-3">Percentage</th>
                                <th scope="col" class="px-6 py-3">Payment Status</th>
                                <th scope="col" class="px-6 py-3">Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for milestone in offer_data.all_offer_milestones %}
                                <tr class="bg-white border-b dark:bg-black dark:border-gray-700">
                                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        {{ milestone.milestone_number }}
                                    </th>
                                    <td class="px-6 py-4">
                                        {{ milestone.percentage }}
                                    </td>
                                    <td class="px-6 py-4">
                                        {% if milestone.paid %}
                                            Paid
                                        {% else %}
                                            Not Paid
                                        {% endif %}
                                    </td>
                                    <td class="px-6 py-4">
                                        ${{ milestone.ammount }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                {% endif %}

                
                {% if offer_data.next_milestone %}
                <div class="mt-10">
                
                    <div class="border-b border-gray-400 dark:border-gray-700">
                        <p class="text-xl md:text-2xl leading-snug md:leading-snug font-Roboto tracking-wide font-light text-black dark:text-white mb-2">Total: <strong class="font-bold">$ {{ offer_data.total_ammount }}</strong></p>
                    </div>

                        <div class="mt-6 border-b border-gray-400 dark:border-gray-700">
                            <p class="text-xl md:text-2xl leading-snug md:leading-snug font-Roboto tracking-wide font-light text-black dark:text-white mb-2">Remaining to Pay: <strong class="font-bold">$ {{ offer_data.remaining_ammount }}</strong></p>
                        </div>

                        <div class="mt-6 border-b border-gray-400 dark:border-gray-700">
                            <p class="text-xl md:text-2xl leading-snug md:leading-snug font-Roboto tracking-wide font-light text-black dark:text-white mb-2">Current Milestone: <strong class="font-bold">{{ offer_data.next_milestone.milestone_number }}</strong></p>
                        </div>
                        
                        <div class="mt-6 border-b border-gray-400 dark:border-gray-700">
                            <p class="text-xl md:text-2xl leading-snug md:leading-snug font-Roboto tracking-wide font-light text-black dark:text-white mb-2">Milestone Amount: <strong class="font-bold">$ {{ offer_data.next_milestone.ammount }}</strong></p>
                        </div>

                      
                        <div class="mt-10">
                           
                            <form method="post" action="{% url 'user_profile:offers-billing' %}">
                                {% csrf_token %}
                                <!-- Add hidden fields with the required details -->
                                <input type="hidden" name="next_milestone_id" value="{{ offer_data.next_milestone.id }}">
                                
                                    <button type="submit" class="text-xl font-Inter font-normal text-white dark:text-black bg-black dark:bg-white py-5 px-24 exsm:px-28 hover:bg-slate-900 dark:hover:bg-slate-100">Pay Now</button>
                                  
                            </form> 
                              
                              
                      </div>

                    </div>

                    {% endif %}   

            </div>
        {% endfor %}




<!-- Communication platforms related -->
<div>
<div class="mt-12">
    <div class="text-2xl md:text-3xl font-Lato font-bold text-black dark:text-white"><p>Communication platforms</p></div>
</div>

<div class="flex flex-wrap gap-4 md:gap-10 m-2 mt-8">  
    <div class="w-60">
        <a href="https://wa.me/918431944801?text=Hello%20from%20websiteWhatsapp" class="py-2 px-4 border border-black dark:border-gray-300 rounded-full flex items-center w-full hover:bg-slate-100 dark:hover:bg-slate-950">
            <?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg"  class="h-10 w-10 fill-black dark:fill-white" alt="Whatsapp" viewBox="0 0 50 50" width="25px" height="25px">    <path d="M25,2C12.318,2,2,12.318,2,25c0,3.96,1.023,7.854,2.963,11.29L2.037,46.73c-0.096,0.343-0.003,0.711,0.245,0.966 C2.473,47.893,2.733,48,3,48c0.08,0,0.161-0.01,0.24-0.029l10.896-2.699C17.463,47.058,21.21,48,25,48c12.682,0,23-10.318,23-23 S37.682,2,25,2z M36.57,33.116c-0.492,1.362-2.852,2.605-3.986,2.772c-1.018,0.149-2.306,0.213-3.72-0.231 c-0.857-0.27-1.957-0.628-3.366-1.229c-5.923-2.526-9.791-8.415-10.087-8.804C15.116,25.235,13,22.463,13,19.594 s1.525-4.28,2.067-4.864c0.542-0.584,1.181-0.73,1.575-0.73s0.787,0.005,1.132,0.021c0.363,0.018,0.85-0.137,1.329,1.001 c0.492,1.168,1.673,4.037,1.819,4.33c0.148,0.292,0.246,0.633,0.05,1.022c-0.196,0.389-0.294,0.632-0.59,0.973 s-0.62,0.76-0.886,1.022c-0.296,0.291-0.603,0.606-0.259,1.19c0.344,0.584,1.529,2.493,3.285,4.039 c2.255,1.986,4.158,2.602,4.748,2.894c0.59,0.292,0.935,0.243,1.279-0.146c0.344-0.39,1.476-1.703,1.869-2.286 s0.787-0.487,1.329-0.292c0.542,0.194,3.445,1.604,4.035,1.896c0.59,0.292,0.984,0.438,1.132,0.681 C37.062,30.587,37.062,31.755,36.57,33.116z"/></svg>
            <p class="text-xl font-medium ml-4 text-black dark:text-white">Whatsapp</p>
          </a>
    </div>


    <div class="w-60">
        <a href="https://discord.gg/e3tkke4AQE" class="py-2 px-4 border border-black dark:border-gray-300 rounded-full flex items-center w-full hover:bg-slate-100 dark:hover:bg-slate-950">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 fill-black dark:fill-white" viewBox="0 0 127.14 96.36"><path d="M107.7,8.07A105.15,105.15,0,0,0,81.47,0a72.06,72.06,0,0,0-3.36,6.83A97.68,97.68,0,0,0,49,6.83,72.37,72.37,0,0,0,45.64,0,105.89,105.89,0,0,0,19.39,8.09C2.79,32.65-1.71,56.6.54,80.21h0A105.73,105.73,0,0,0,32.71,96.36,77.7,77.7,0,0,0,39.6,85.25a68.42,68.42,0,0,1-10.85-5.18c.91-.66,1.8-1.34,2.66-2a75.57,75.57,0,0,0,64.32,0c.87.71,1.76,1.39,2.66,2a68.68,68.68,0,0,1-10.87,5.19,77,77,0,0,0,6.89,11.1A105.25,105.25,0,0,0,126.6,80.22h0C129.24,52.84,122.09,29.11,107.7,8.07ZM42.45,65.69C36.18,65.69,31,60,31,53s5-12.74,11.43-12.74S54,46,53.89,53,48.84,65.69,42.45,65.69Zm42.24,0C78.41,65.69,73.25,60,73.25,53s5-12.74,11.44-12.74S96.23,46,96.12,53,91.08,65.69,84.69,65.69Z"/></svg>
            <p class="text-xl font-medium ml-4 text-black dark:text-white">Discord</p>
          </a>
    </div>


    <div class="w-60">
        <a href="https://teams.live.com/l/invite/FEAY_545gm0xbaRvQE" class="py-2 px-4 border border-black dark:border-gray-300 rounded-full flex items-center w-full hover:bg-slate-100 dark:hover:bg-slate-950">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 fill-black dark:fill-white" alt="" viewBox="0 0 30 30" width="25px" height="25px"><path d="M 16.5 3 A 3.5 3.5 0 0 0 13.339844 8 L 4 8 C 2.895 8 2 8.895 2 10 L 2 20 C 2 21.105 2.895 22 4 22 L 14 22 C 15.105 22 16 21.105 16 20 L 16 10 C 16 9.987256 15.996331 9.9755777 15.996094 9.9628906 A 3.5 3.5 0 0 0 16.5 10 A 3.5 3.5 0 1 0 16.5 3 z M 24 5 A 2.5 2.5 0 0 0 24 10 A 2.5 2.5 0 0 0 24 5 z M 6 11 L 8.5 11 L 9.5 11 L 12 11 L 12 12 L 9.5 12 L 9.5 19 L 8.5 19 L 8.5 12 L 6 12 L 6 11 z M 18 12 L 18 20 C 18 22.21 16.21 24 14 24 L 11.019531 24 C 12.179531 25.8 14.2 27 16.5 27 C 20.09 27 23 24.09 23 20.5 L 23 14 C 23 12.9 22.1 12 21 12 L 18 12 z M 24.460938 12 C 24.800938 12.59 25 13.27 25 14 L 25 20.5 C 25 21.35 24.880625 22.169453 24.640625 22.939453 C 26.550625 22.639453 28 20.99 28 19 L 28 14 C 28 12.9 27.1 12 26 12 L 24.460938 12 z"/></svg>
            <p class="text-xl font-medium ml-4 text-black dark:text-white">Microsoft Teams</p>
          </a>
    </div>


    <div class="w-60">
        <a href="https://app.slack.com/huddle/T05USEC8WTF/C065XRER92T" class="py-2 px-4 border border-black dark:border-gray-300 rounded-full flex items-center w-full hover:bg-slate-100 dark:hover:bg-slate-950">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 fill-black dark:fill-white" alt="" viewBox="0 0 50 50" width="25px" height="25px"><path d="M31 24c-2.757 0-5-2.243-5-5V7c0-2.757 2.243-5 5-5s5 2.243 5 5v12C36 21.757 33.757 24 31 24zM43 24h-4c-.553 0-1-.447-1-1v-4c0-2.757 2.243-5 5-5s5 2.243 5 5S45.757 24 43 24zM19 24H7c-2.757 0-5-2.243-5-5s2.243-5 5-5h12c2.757 0 5 2.243 5 5S21.757 24 19 24zM23 12h-4c-2.757 0-5-2.243-5-5s2.243-5 5-5 5 2.243 5 5v4C24 11.553 23.553 12 23 12zM19 48c-2.757 0-5-2.243-5-5V31c0-2.757 2.243-5 5-5s5 2.243 5 5v12C24 45.757 21.757 48 19 48zM7 36c-2.757 0-5-2.243-5-5s2.243-5 5-5h4c.553 0 1 .447 1 1v4C12 33.757 9.757 36 7 36zM43 36H31c-2.757 0-5-2.243-5-5s2.243-5 5-5h12c2.757 0 5 2.243 5 5S45.757 36 43 36zM31 48c-2.757 0-5-2.243-5-5v-4c0-.553.447-1 1-1h4c2.757 0 5 2.243 5 5S33.757 48 31 48z"/></svg>
            <p class="text-xl font-medium ml-4 text-black dark:text-white">Slack</p>
          </a>
    </div>
    </div>
</div>



{% else %}
        <div class="sm:mt-32">
            <div>
                <div>
                    <p class="text-5xl md:text-6xl leading-snug md:leading-snug font-Inter font-bold tracking-wide text-black dark:text-white">You don't have any offers yet.</p>
                </div>
                <div class="flex gap-4 xl:gap-12 max-xl:flex-col flex-row lg:ml-2">
                    <div class="my-12">
                        <a href="{% url 'user_profile:make-offer' %}" class="text-xl font-Inter font-light text-white dark:text-black bg-black dark:bg-white py-5 px-24 hover:bg-slate-900 dark:hover:bg-slate-100 border border-black dark:border-white rounded-full">Make Offer</a>
                    </div>
                   
                    <div class="xl:my-12">
                        <a href="{% url 'home:contact' %}" class="text-xl font-Inter font-light text-black dark:text-white border border-black dark:border-white py-5 px-24 rounded-full hover:bg-black dark:hover:bg-white hover:text-white dark:hover:text-black">Contact us</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% endblock profile-content %}

user_profile/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyCoes Profile{% endblock title %}
{% block meta_description %}Manage your offers, Billings, and Transactions through profile page.{% endblock meta_description %}

{% block content %}

<div class="w-full flex justify-center">
    <div class="w-full lg:w-9/12">
   
    

      <div>
         <button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar" type="button" class="inline-flex items-center p-2 mt-20 ml-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
             <span class="sr-only">Open sidebar</span>
             <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                 <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
             </svg>
         </button>

         <aside id="default-sidebar" class="fixed z-40 left-0 w-64 transform -translate-x-full sm:translate-x-0 border-r border-gray-400 dark:border-gray-900 bg-white dark:bg-black" aria-label="Sidebar">
             <div class="h-full px-4 py-4 overflow-y-auto mt-16">
                <div>
                <button type="button" data-drawer-hide="default-sidebar" aria-controls="default-sidebar" class="sm:hidden text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 absolute end-2.5 inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" >
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    <span class="sr-only">Close menu</span>
                </button>
                </div>
                 <ul class="space-y-2 font-medium mt-10">

                     <li>
                         <a href="{% url 'user_profile:offers-billing' %}" class="flex items-center p-2 text-gray-900 text-xl font-Roboto tracking-wider font-light rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-800 group">
                             <span class="ml-3">Offers & Billing</span>
                         </a>
                     </li>
                     

                     <li>
                        <a href="{% url 'user_profile:transctions' %}" class="flex items-center p-2 text-gray-900 text-xl font-Roboto tracking-wider font-light rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-800 group">
                            <span class="flex-1 ml-3 whitespace-nowrap">Transactions</span>
                        </a>
                    </li>

                     <li>
                         <a href="{% url 'custom_logout' %}" class="flex items-center p-2 text-gray-900 text-xl font-Roboto tracking-wider font-light rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-800 group">
                             <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 16">
                                 <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"/>
                             </svg>
                             <span class="flex-1 ml-3 whitespace-nowrap">Sign Out</span>
                         </a>
                     </li>

                 </ul>
             </div>
         </aside>

     </div>
         

     <div class="sm:ml-60 sm:mr-2 lg:ml-36 xl:ml-28 sm:mt-28">
        <div class="sm:ml-6">
     {% block profile-content %}
      
     {% endblock profile-content %}  
    </div>
    </div>
     

  </div>
  </div>



{% endblock content %}